name: GitHub Actions Training (CD)
on:
  push:
    branches:
      - main

jobs:
  cd:
    name: Deploy Azure Static Website
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: 0566f5b6-debf-45fd-8f3c-58fa8884daed
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ff3d879c-06ae-4b49-ad1f-1c8825837d91
      ARM_TENANT_ID: 68f381e3-46da-47b9-ba57-6f322b8f0da1

    steps:
      - name: Ensure that NetID is set
        run: |
          if [ -z "${{ secrets.NETID }}" ]
          then
            echo "NETID is not set"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.4

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init -backend-config="key=${{ secrets.NETID}}/terraform.tfstate"

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -var="netid=${{ secrets.NETID }}"

      - name: Create Issue for a failed deployment
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Action workflow failed.
          body: |
            ### Context
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
            Workflow name - `${{ github.workflow }}`
            Job -           `${{ github.job }}`
            status -        `${{ job.status }}`
